# Generated by Django 3.0.5 on 2020-05-09 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_auto_20200509_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='submitter',
        ),
    ]
